"""FastAPI application scaffolding for PhishGuard."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException

from .schemas import URLRequest, URLResponse
from ..features import extract_all_features


app = FastAPI(title="PhishGuard API", version="0.1.0")

_MODEL_PATH = Path(__file__).resolve().parents[2] / "models" / "baseline_model.pkl"
_baseline_model: Optional[object] = None


def _load_baseline_model() -> Optional[object]:
    """Load the baseline model from disk if available."""

    if not _MODEL_PATH.exists():
        return None
    try:
        return joblib.load(_MODEL_PATH)
    except Exception:  # pragma: no cover - defensive fallback
        return None


_baseline_model = _load_baseline_model()


@app.get("/health", response_model=dict)
def health_check() -> dict:
    """Health probe endpoint to verify service availability."""
    # TODO: Enhance with dependency checks (model load status, external services).
    status = "ok" if _baseline_model is not None else "degraded"
    return {"status": status}


@app.post("/predict", response_model=URLResponse)
def predict_url(payload: URLRequest) -> URLResponse:
    """Return a phishing prediction for the provided URL using the baseline model."""
    if _baseline_model is None:
        raise HTTPException(
            status_code=503,
            detail="Baseline model is unavailable. Retrain or deploy an updated model.",
        )

    try:
        features = extract_all_features(payload.url)
        feature_frame = pd.DataFrame([features])

        prediction = _baseline_model.predict(feature_frame)[0]
        probabilities = getattr(_baseline_model, "predict_proba", None)
        phishing_probability = 0.0
        if callable(probabilities):
            phishing_probability = float(probabilities(feature_frame)[0][1])

        # TODO: Replace baseline logic with production-grade ensemble or deep model.
        return URLResponse(
            url=payload.url,
            prediction_label=int(prediction),
            score=float(phishing_probability),
            message="Prediction generated by baseline model",
        )
    except HTTPException:
        raise
    except Exception as exc:  # pragma: no cover - defensive fallback
        raise HTTPException(
            status_code=500,
            detail=f"Prediction failed: {exc}",
        )
